# Generated by Django 5.2.11 on 2026-04-01 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_halls', '0001_initial'),
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examhall',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_halls', to='faculties.faculty'),
            preserve_default=False,
        ),
    ]
