# Generated by Django 5.2.11 on 2026-04-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_halls', '0002_examhall_faculty'),
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examhall',
            unique_together={('name', 'faculty')},
        ),
    ]
