# Generated by Django 5.2.11 on 2026-04-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsessionuser',
            name='academic_rank',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Senior Assistant', 'Senior Assistant'), ('Assistant', 'Assistant'), ('Student', 'Student')], max_length=30),
        ),
    ]
