# Generated by Django 5.2.11 on 2026-04-07 09:52

from django.db import migrations
from django.contrib.auth.management import create_permissions


def create_groups_and_permissions(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    group_model = apps.get_model('auth', 'Group')
    permission_model = apps.get_model('auth', 'Permission')

    group_permissions_map = {
        'Teacher': [
            'view_examhall',
            'view_major',
            'view_faculty',
            'add_exam',
            'change_exam',
            'delete_exam',
            'view_exam',
        ],
        'Student': [
            'view_exam',
            'view_faculty',
            'view_major',
        ],
    }

    for group_name, permission_codenames in group_permissions_map.items():
        group, created = group_model.objects.get_or_create(name=group_name)

        permissions = permission_model.objects.filter(codename__in=permission_codenames)

        group.permissions.set(permissions)


def revert_groups_and_permissions(apps, schema_editor):
    group_model = apps.get_model('auth', 'Group')
    group_model.objects.filter(name__in=['Teacher', 'Student']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_alter_examsessionuser_academic_rank'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exam_halls', '0002_examhall_faculty'),
        ('exams', '0001_initial'),
        ('majors', '0002_major_faculty'),
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions, revert_groups_and_permissions),
    ]