# Generated by Django 6.0.2 on 2026-02-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='exam.exam')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
