# Generated by Django 6.0.2 on 2026-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_halls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('needs_computers', models.BooleanField(default=False)),
                ('number_of_examinees', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_halls', models.ManyToManyField(related_name='hosted_exams', to='exam_halls.examhall')),
            ],
        ),
    ]
