# Generated by Django 5.2.11 on 2026-03-17 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_halls', '0001_initial'),
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=50)),
                ('needs_computers', models.BooleanField(default=False)),
                ('number_of_examinees', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_halls', models.ManyToManyField(related_name='hosted_exams', to='exam_halls.examhall')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='majors.major')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('subject', 'major')},
            },
        ),
    ]
